name: Build Release

on:
  push:
    branches: [ "master", "feature/*" ]
  workflow_dispatch:

jobs:

# ================= ANDROID =================
  build-android:
    name: Build Android ARM64 APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build ObjectBox
        run: |
          flutter pub run build_runner clean
          flutter pub run build_runner build --delete-conflicting-outputs

      # استخراج الإصدار من pubspec.yaml
      - name: Get App Version
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d+ -f1)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      # إعداد Keystore
      - name: Setup Android keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/release.keystore

          cat > android/key.properties <<EOF
          storeFile=release.keystore
          storePassword=$ANDROID_KEYSTORE_PASSWORD
          keyPassword=$ANDROID_KEY_PASSWORD
          keyAlias=$ANDROID_KEY_ALIAS
          EOF

      # بناء APK ARM64 فقط
      - name: Build Android APK ARM64
        run: flutter build apk --release --target-platform android-arm64

      # إعادة تسمية APK باسم التطبيق + الإصدار
      - name: Rename APK
        run: |
          APP_NAME="Alrwah"
          mv build/app/outputs/flutter-apk/app-release.apk \
          build/app/outputs/flutter-apk/${APP_NAME}_v${APP_VERSION}_arm64.apk

      # رفع Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Alrwah-arm64
          path: build/app/outputs/flutter-apk/Alrwah_v${{ env.APP_VERSION }}_arm64.apk
